from app.services.nutrition.knowledge import (
    FOODS_JSONL_PATH,
    MASTER_JSONL_PATH,
    QDRANT_READY_JSONL_PATH,
    CanonicalKnowledgeService,
    ascii_normalize,
    build_canonical_content,
    build_dense_text,
    build_hybrid_text,
    build_sparse_text,
    build_vector_payload,
    canonical_knowledge_service,
    default_runtime_jsonl_path,
    derive_allergen_tags,
    derive_diet_tags,
    format_metric,
    is_qdrant_ready_record,
    normalize_unicode_text,
    normalized_tokens,
    payload_to_food,
    raw_normalize,
    raw_tokens,
    safe_float,
    sanitize_json_payload,
)

# NEW: Re-export improved role-aware filter builder (used by workflow for ~99% tag hit + higher precision/recall)
from app.services.nutrition.knowledge.qdrant_filters import QdrantFilterMixin

__all__ = [
    "FOODS_JSONL_PATH",
    "MASTER_JSONL_PATH",
    "QDRANT_READY_JSONL_PATH",
    "CanonicalKnowledgeService",
    "QdrantFilterMixin",  # exposes enhanced filter with expected_role_tags support
    "ascii_normalize",
    "build_canonical_content",
    "build_dense_text",
    "build_hybrid_text",
    "build_sparse_text",
    "build_vector_payload",
    "canonical_knowledge_service",
    "default_runtime_jsonl_path",
    "derive_allergen_tags",
    "derive_diet_tags",
    "format_metric",
    "is_qdrant_ready_record",
    "normalize_unicode_text",
    "normalized_tokens",
    "payload_to_food",
    "raw_normalize",
    "raw_tokens",
    "safe_float",
    "sanitize_json_payload",
]
