RAW_SEMANTIC_GOAL_ALIASES = {
    "gain_weight_general": "gain_weight_general",
    "gain_weight": "gain_weight_general",
    "weight_gain": "gain_weight_general",
    "gain": "gain_weight_general",
    "tang_can": "gain_weight_general",
    "len_can": "gain_weight_general",
    "tang_can_sach": "gain_weight_general",
    "gain_muscle": "gain_muscle",
    "muscle_gain": "gain_muscle",
    "bulking": "gain_muscle",
    "bulk": "gain_muscle",
    "tang_co": "gain_muscle",
    "xay_co": "gain_muscle",
    "lose_weight_general": "lose_weight_general",
    "lose_weight": "lose_weight_general",
    "weight_loss": "lose_weight_general",
    "giam_can": "lose_weight_general",
    "xuong_can": "lose_weight_general",
    "fat_loss": "fat_loss",
    "cutting": "fat_loss",
    "cut": "fat_loss",
    "giam_mo": "fat_loss",
    "siet_mo": "fat_loss",
    "maintain": "maintain",
    "maintenance": "maintain",
    "giu_can": "maintain",
    "can_bang": "maintain",
    "eat_healthier": "eat_healthier",
    "healthy": "eat_healthier",
    "an_lanh_manh": "eat_healthier",
    "song_khoe": "eat_healthier",
    "support_training": "support_training",
    "training_support": "support_training",
    "ho_tro_tap_luyen": "support_training",
    "tap_tot_hon": "support_training",
}

RAW_SEMANTIC_GOAL_HINTS = {
    "gain_weight_general": [
        "tang can",
        "len can",
        "gain weight",
        "weight gain",
        "put on weight",
        "day dan hon",
        "day hon",
        "nguoi day hon",
        "nguoi ay hon",
        "hoi gay",
    ],
    "gain_muscle": [
        "tang co",
        "gain muscle",
        "muscle gain",
        "muscle building",
        "bulk",
        "bulking",
        "xay co",
        "len co",
    ],
    "lose_weight_general": [
        "giam can",
        "xuong can",
        "bot can",
        "giam can de theo",
        "giam can nhe nhang",
        "lose weight",
        "nhe can hon",
    ],
    "fat_loss": [
        "giam mo",
        "fat loss",
        "cutting",
        "cut",
        "deficit",
        "siet mo",
        "gon nguoi",
        "khong bi doi",
        "khong doi",
        "an no lau",
        "lean hon",
    ],
    "maintain": ["giu can", "duy tri", "maintain", "maintenance", "can bang"],
    "eat_healthier": [
        "an lanh manh",
        "an sach hon",
        "an khoe",
        "khoe hon",
        "healthy",
        "tot cho suc khoe",
        "an tot cho suc khoe",
        "lanh manh de duy tri",
        "eat healthier",
        "eat healthy",
    ],
    "support_training": [
        "tap tot hon",
        "tap co suc",
        "tap co suc hon",
        "ho tro tap luyen",
        "support training",
        "performance",
        "phuc hoi",
        "phuc hoi cho nguoi moi tap",
        "sau tap",
        "bua sau tap",
        "post workout",
    ],
}

GOAL_ALIASES = {
    "gain_muscle": "gain_muscle",
    "gain": "gain_muscle",
    "gain_weight": "gain_muscle",
    "weight_gain": "gain_muscle",
    "bulking": "gain_muscle",
    "bulk": "gain_muscle",
    "tang_co": "gain_muscle",
    "tang_can": "gain_muscle",
    "tang_can_sach": "gain_muscle",
    "len_can": "gain_muscle",
    "lose_weight": "lose_weight",
    "fat_loss": "lose_weight",
    "cutting": "lose_weight",
    "cut": "lose_weight",
    "giam_can": "lose_weight",
    "giam_mo": "lose_weight",
    "siet_can": "lose_weight",
    "maintain": "maintain",
    "maintenance": "maintain",
    "giu_can": "maintain",
    "can_bang": "maintain",
}

RAW_TO_INTERNAL_GOAL = {
    "gain_weight_general": "gain_muscle",
    "gain_muscle": "gain_muscle",
    "lose_weight_general": "lose_weight",
    "fat_loss": "lose_weight",
    "maintain": "maintain",
    "eat_healthier": "maintain",
    "support_training": "maintain",
}

RAW_TO_DEFAULT_STRATEGY = {
    "gain_weight_general": "surplus_balanced",
    "gain_muscle": "surplus_high_protein",
    "lose_weight_general": "deficit_balanced",
    "fat_loss": "deficit_high_satiety",
    "maintain": "maintenance_balanced",
    "eat_healthier": "maintenance_health_support",
    "support_training": "maintenance_training_support",
}

PLANNING_STRATEGY_ALIASES = {
    "surplus_balanced": "surplus_balanced",
    "surplus_high_protein": "surplus_high_protein",
    "deficit_balanced": "deficit_balanced",
    "deficit_high_satiety": "deficit_high_satiety",
    "maintenance_balanced": "maintenance_balanced",
    "maintenance_health_support": "maintenance_health_support",
    "maintenance_training_support": "maintenance_training_support",
}

DIETARY_ALIASES = {
    "omnivore": "omnivore",
    "an_tap": "omnivore",
    "vegetarian": "vegetarian",
    "an_chay": "vegetarian",
    "vegan": "vegan",
    "thuan_chay": "vegan",
    "pescatarian": "pescatarian",
    "an_ca": "pescatarian",
}

ALLERGY_ALIASES = {
    "sua": "dairy",
    "milk": "dairy",
    "dairy": "dairy",
    "trung": "egg",
    "egg": "egg",
    "dau_nanh": "soy",
    "soy": "soy",
    "dau_phong": "peanut",
    "lac": "peanut",
    "peanut": "peanut",
    "hat_dieu": "tree_nut",
    "hanh_nhan": "tree_nut",
    "tree_nut": "tree_nut",
    "gluten": "gluten",
    "lua_mi": "gluten",
    "wheat": "gluten",
    "tom": "shellfish",
    "cua": "shellfish",
    "shellfish": "shellfish",
    "fish": "fish",
    "ca": "fish",
    "me": "sesame",
    "sesame": "sesame",
}

PRIORITY_ALIASES = {
    "protein": "protein",
    "dam": "protein",
    "high_protein": "protein",
    "satiety": "satiety",
    "no_lau": "satiety",
    "no_bung": "satiety",
    "recovery": "recovery",
    "phuc_hoi": "recovery",
    "simplicity": "simplicity",
    "de_nau": "simplicity",
    "don_gian": "simplicity",
    "budget": "budget",
    "ngan_sach": "budget",
    "variety": "variety",
    "da_dang": "variety",
    "lightness": "lightness",
    "thanh_dam": "lightness",
    "micronutrients": "micronutrients",
    "vitamin": "micronutrients",
    "digestion": "digestion",
    "de_tieu": "digestion",
}

COOKING_COMPLEXITY_ALIASES = {
    "easy": "easy",
    "simple": "easy",
    "de_nau": "easy",
    "de_lam": "easy",
    "nhanh": "easy",
    "medium": "medium",
    "vua": "medium",
    "any": "any",
    "bat_ky": "any",
}

BUDGET_LEVEL_ALIASES = {
    "low": "low",
    "re": "low",
    "ngan_sach": "low",
    "tiet_kiem": "low",
    "medium": "medium",
    "vua": "medium",
    "high": "high",
    "cao_cap": "high",
}

MEAL_STYLE_ALIASES = {
    "simple": "simple",
    "don_gian": "simple",
    "traditional": "traditional",
    "truyen_thong": "traditional",
    "high_protein": "high_protein",
    "light": "light",
    "thanh_dam": "light",
    "balanced": "balanced",
    "can_bang": "balanced",
}

SATIETY_ALIASES = {
    "high": "high",
    "no_lau": "high",
    "normal": "normal",
    "light": "light",
}

PRIORITY_HINTS = {
    "protein": ["protein", "dam", "giau dam", "high protein"],
    "satiety": ["no lau", "khong doi", "no bung", "satiety"],
    "recovery": ["sau tap", "post workout", "phuc hoi", "recovery"],
    "simplicity": ["de nau", "de lam", "nhanh", "don gian"],
    "budget": ["ngan sach", "gia re", "tiet kiem"],
    "variety": ["da dang", "doi mon", "nhieu lua chon"],
    "lightness": ["thanh dam", "it dau mo", "nhe bung"],
    "micronutrients": ["vitamin", "khoang chat", "vi chat"],
    "digestion": ["de tieu", "nhe bung"],
}

CHAT_CLARIFY_GOALS = {
    "gain_weight_general": "clarify_gain_weight",
    "lose_weight_general": "clarify_lose_weight",
    "eat_healthier": "clarify_eat_healthier",
}
